---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
env:
  - PUPPET_VERSION=3.8 ONLY_OS=ubuntu-12-x86_64,ubuntu-12.04-x86_64,redhat-6-x86_64,centos-6-x86_64 STRICT_VARIABLES=yes
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
script: bundle exec rake test
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
